services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    networks:
      - scraping
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    
    networks:
      - scraping

networks:
  scraping:
    driver: bridge